### ISSUE TITLE
Define pipeline display name in yaml file?

### ISSUE THREAD

**Issue by haymansfield** [microsoft/azure-pipelines-yaml#244]
Is there any reason the display name of the pipeline could not be defined in the yaml?

**Comment by MichaKnoe** [comment]
The expected behavior definetly would be, that the pipeline name can be configured in the yaml file directly. Also, I would expect that there is NO manuel UI configuration step needed to define multiple deployment pipelines in one repository beside the default one (azure-pipelines.yml wathever) that is automatically detected. Thats why there should also be a flag in yaml to tell AzureDevOps that the pipeline is enabled/paused/disable.
