### ISSUE TITLE
Manual Intervention step in multi stage pipeline

### ISSUE THREAD

**Issue by kmr0877** [microsoft/azure-pipelines-yaml#301]
[docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-intervention?view=azure-devops&viewFallbackFrom=vsts#demands) says that manual intervention step is not available for build pipeline and is available only for releases.
Having said that, when using multi- stage pipeline builds using yaml, its quite disappointing that we cannot include this step and thereby forcing us to create a separate release pipeline just for this step.
What are the alternatives that I have to add them in my `azure-pipelines.yml` file if I were to add a pre-deployment step which includes manual human verification step to QA stage?
Relevant issues can be found below raised already if this issue could possibly be an extension/duplicate of the one's below:
- [Issue-1](https://developercommunity.visualstudio.com/content/problem/358418/cant-find-manual-intervention-task.html)
- [Issue-2](https://github.com/MicrosoftDocs/vsts-docs/issues/4826)
Also, why should this step be an Agentless job in first place?

**Comment by kmr0877** [comment]
I have tried that already.Build fails with the error shown below:
`manual_intervention_step: "Task execution section of task definition for ID: *** is either missing or not valid."
`
Seems like Azure pipelines doesn't pick it up/recognize this task from yaml script in build pipeline.The task that I have added is shown below:
![image](https://user-images.githubusercontent.com/26761582/64083737-58674800-cd67-11e9-8d02-cf771153c7c7.png)

But the same stage works when i drag and drop in  the release pipeline and the schema is exactly the same.
Another point to mention is that its mentioned in the [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-intervention?view=azure-devops&viewFallbackFrom=vsts#demands) as follows - `Can be used in only an agentless job of a release pipeline. This task is not supported in a build pipeline.`

**Comment by nerijusk** [comment]
Yes, please add manual intervention step support to azure-pipelines.yaml.

**Comment by patrickc91** [comment]
This should really be a feature. Every CI/CD platform I've used has the concept of a stop for manual approval.

I'd like to add manual approval gates in places outside of deployments to environments. I don't see how MS thought only adding checks to environment deployments was sufficient.

**Comment by pijemcolu** [comment]
As a workaround to stop/start or skip stages we've used multi stage variables.

We'd define a "stage control" variable in the first stage and depending on it's value we'd execute the consecutive stage or skip it. This is particularly useful in Infrastructure as Code settings where depending on planned changes you might want to execute a release or skip it.

More info about passing variables across stages can be found here: https://stefanstranger.github.io/2019/06/26/PassingVariablesfromStagetoStage/ . I concur it's super hacky as it modifies pipelines using the Aure DevOps pipelines as they're running ..., but it's a workaround. Shows how much a manual intervention step is needed when people come up with these. :)

**Comment by dansali** [comment]
I can't understand how this isn't a thing. I just ran into this issue and cannot proceed with my pipeline development anymore...

Please allow Manual Interventions to be apart of Build pipelines.

**Comment by patrickc91** [comment]
Just an update here. The lack of manual intervention was a hard blocker for us. We ended up dropping Azure Pipelines and writing everything in Jenkins.

We didn't want to use Jenkins for our CD, but we already had it sitting around for some CI jobs.

Maybe one day we'll consider returning to Azure DevOps, but there are some really simple tasks they are lacking. Manual Approvals outside of Environments being a huge one.

**Comment by sesispla** [comment]
We've been deeply investigating how environments and deployment works and looks like is possible to have the "manual intervention" behaviour in YAML pipelines.

It took a while to understand how it works, as all the puzzle pieces are documented separately, so the problem is the documentation, not the lack of functionality.

The process would be:
1. [Create an environment](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops)
1. [Add manual approval to your environment](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops#approvals)
1. Create a YAML pipeline as usual
1. [Create a deployment job](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops#target-an-environment-from-a-deployment-job)
1. Include the environment name you created in "1." to the [deployment "environment" property](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#runonce-deployment-strategy-1)

When you do this, Azure DevOps will automatically wait in any task that tries to deploy to this environment. You can even add more deployment gates, which is really nice!!

![screenshot](https://user-images.githubusercontent.com/8591052/77848800-48a9c800-71bf-11ea-8919-7299d37ec6ac.png)

I believe this issue can be closed.

**Comment by adriantorrie** [comment]
> We've been deeply investigating how environments and deployment works and looks like is possible to have the "manual intervention" behaviour in YAML pipelines.
> 
> It took a while to understand how it works, as all the puzzle pieces are documented separately, so the problem is the documentation, not the lack of functionality.
> 
> The process would be:
> 
> 1. [Create an environment](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops)
> 2. [Add manual approval to your environment](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops#approvals)
> 3. Create a YAML pipeline as usual
> 4. [Create a deployment job](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops#target-an-environment-from-a-deployment-job)
> 5. Include the environment name you created in "1." to the [deployment "environment" property](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#runonce-deployment-strategy-1)
> 
> When you do this, Azure DevOps will automatically wait in any task that tries to deploy to this environment. You can even add more deployment gates, which is really nice!!
> 
> ![screenshot](https://user-images.githubusercontent.com/8591052/77848800-48a9c800-71bf-11ea-8919-7299d37ec6ac.png)
> 
> I believe this issue can be closed.

What you've proposed is a "Check" before deploying to an "Environment".

This is not the same as a manual intervention task.

This issue needs to remain open imo.

**Comment by sesispla** [comment]
In our case, each "Plan/Apply" is part of the same "stage". We had to split in two, to have the ability to review a Terraform plan (as we did with manual intervention in the past).

This is not exactly the same behaviour, but creating two stages that deploy to the same environment do the job and we've been able to start migrating all our Releases to YAML pipelines.

**Comment by nerijusk** [comment]
> In our case, each "Plan/Apply" is part of the same "stage". We had to split in two, to have the ability to review a Terraform plan (as we did with manual intervention in the past).
> 
> This is not exactly the same behaviour, but creating two stages that deploy to the same environment do the job and we've been able to start migrating all our Releases to YAML pipelines.

Your suggestion makes all pipelines to wait for approvals when applied to the environment. This is not feasible in my case. I need only a specific pipeline to stop in the middle and wait for approval. All other pipelines to that same environment should run to the end automatically without interruptions.

**Comment by davegoopot** [comment]
> 
> 
> In order to consolidate to fewer feedback channels, we've moved suggestions and issue reporting to [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). Sorry for any confusion resulting from this move.

Looks like the matching ticket is: https://developercommunity.visualstudio.com/idea/567850/support-manual-intervention-task-for-multi-stage-p.html

**Comment by silviulucacentriceu** [comment]
Because there's a long time since Microsoft is ignoring this, and because this is a critical missing functionality , I will add an workaround here (for the moment, it's working only to ignore the entire step for all machines in case of a multi stage YAML but I think this can be solved also, but I am not looking into it for the moment).

Unfortunately, there is a task that needs to be added before each task. This can be solved also by iterative insertion (https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops).

Shortly, in order to be able to ignore a specific task:
- T1 is checking the build run for "IgnoreStep"tag. If found, it will set IgnoreStep variable to true and remove the tag
- T2 is running only if previous IgnoreStep is on false
When something is failing and I want to ignore the step, I will add "IgnoreStep" tag for the run and retry.

For adding tags, I am using the API because there is no task to do it yet. For request details, F21 in Chrome and check what it sent to server after you will add a tag, and export the request to power shell.

Below you have the YAML:


trigger: none

jobs:
- deployment: Dev
environment:
name: Dev
resourceType: virtualMachine
tags: online
strategy:
runOnce:
deploy:
steps:
- task: PowerShell@2
displayName: CheckIfWeShouldIgnoreStep
name: CheckIfWeShouldIgnoreStep
inputs:
targetType: 'inline'
script: |
$user = "user"
$pass= "pass"
$secpasswd = ConvertTo-SecureString $pass -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential($user, $secpasswd)

$response = Invoke-RestMethod -Uri "https://server/tfs/collection/projectId/_apis/build/builds/$(Build.BuildId)/tags" `
-Method "GET" `
-Headers @{
"accept"="application/json;api-version=6.0;excludeUrls=true;enumsAsNumbers=true;msDateFormat=true;noArrayWrap=true"
} `
-ContentType "application/json" `
-Credential $credential -UseBasicParsing

Write-Host "##vso[task.setvariable variable=IgnoreStep]false"

Write-Host "Tags: $response"
foreach($tag in $response)
{
if($tag -eq "IgnoreStep")
{
Write-Host "##vso[task.setvariable variable=IgnoreStep]true"


Invoke-RestMethod -Uri "https://server/tfs/collection/projectId/_apis/build/builds/$(Build.BuildId)/tags/IgnoreStep" `
-Method "DELETE" `
-Headers @{
"accept"="application/json;api-version=6.0;excludeUrls=true;enumsAsNumbers=true;msDateFormat=true;noArrayWrap=true"
}`
-Credential $credential -UseBasicParsing
}
}
- task: PowerShell@2
displayName: Throw Error
condition: eq (variables.IgnoreStep, false)
inputs:
targetType: 'inline'
script: |
throw "Error"

**Comment by matteotumiati** [comment]
It seems quite an interesting workaround, thank you for sharing!

However, I wouldn't say Microsoft is ignoring it... If you look at the roadmap, this is planning to rollout (officially!) in Q4 2020: https://devblogs.microsoft.com/devops/azure-devops-roadmap-update-for-2020-q4/#azure-pipelines 
https://dev.azure.com/mseng/AzureDevOpsRoadmap/_workitems/edit/1663893

**Comment by JFolberth** [comment]
Actually roadmap is outdated...It is available now:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-validation?view=azure-devops&tabs=yaml
