### ISSUE TITLE
Approval on environment when the process is skipped

### ISSUE THREAD

**Issue by maikvandergaag** [microsoft/azure-pipelines-yaml#401]
When setting up an approval on a environment. The approval is checked before the condition added to the job.

I think the condition should be run first before the approval.

**Comment by lbergeron01** [comment]
I faced this issue this morning and I share @maikvandergaag thinking. If condition is evaluated first, and the environment is skipped, then there is no need to request approval.

My use case is a CI/CD process where CI is also use as PR validation.

**Comment by DavoBR** [comment]
i need that feature, now i am realizing that it may be a problem, because i have several deployment setup in the pipeline, each with its own condition and environment and when the pipeline is activated by the PR, azure asks for approval in every environment when only one approval is needed.

The only workarount that i found is splitting the yml
