### ISSUE TITLE
Trigger IaC Pipeline from Commit in either back-end repository or front-end repository

### ISSUE THREAD

**Issue by motowilliams** [microsoft/azure-pipelines-yaml#471]
Here is the scenario and scope of the problem. 

**3 repositories**:
 - infrastructure as code
 - back-end code
 - front-end code

_The dependency chain is that IaC has to be deployed first and both then the back-end and front-end pipelines can start. This is because IaC creates the resources that the back-end and front-end are deployed to but also returns output variables that are used for configuration values for the back-end and front-end deployments._
```
   /- back-end
IaC
   \- front-end
```
We have each repo doing their standard pipeline on commit trigger. That is not problem.
We are also able to to trigger the back-end and front-end pipelines once the IaC pipeline finishes.

What I am not able to figure out is how to **trigger the IaC pipeline** when either a **back-end commit** or **front-end commit** is pushed to their respective repositories.

**Is this feature going to enable this type of workflow?** https://dev.azure.com/mseng/AzureDevOpsRoadmap/_workitems/edit/1454026

**Comment by matteotumiati** [comment]
I might be wrong but as far as I know this scenario is currently unsupported. 
However, have you though about using templates to achieve your scenarios?

What I'm thinking is a bit of a hack for now, but it should work.

**Templates repository**
It should contain the files:
- `build-backend.yml`
- `build-frontend.yml`
- `build-iac.yml`
- `complete.yml`

These first three are used to build (and also deploy, maybe?) backend, frontend and the infrastructure as explicitly said by their names. Anyway each of the files represents a set of operations needed for each part of your architecture. 

`complete.yml` instead represents the build that should:
1. Clone current, IaC, backend and frontend repositories using multi-checkout
1. Build (and deploy) infrastructure, backend and frontend using templates in current repo

**IaC repository**
It should probably contain:
- `iac.yml`
- `validate-infrastructure.yml`
- `check-security.yml`

The last two may not be valid for you. I'm just making up an example to let you know that those are pipelines created specifically for the IaC repo and that aren't referencing anything else outside of the repository. 

`iac.yml` instead can be used to deploy everything (meaning infrastructure, backend and frontend), using the shared template created in the templates repository. It will be probably an empty file that references the shared template using the `extends` keyword. 

**Backend repository** and  **Frontend repository**
You may have, similarly to the IaC repo, different pipelines configured:
- Some that will "execute" something in the local repository
- Some others that will will just extend the behavior using the shared template

I understand that this may not be a suitable approach for you, but this is what I'm doing on my side. I completely removed the pipeline trigger for that scenario because it was a blocker for me and what I described is the workaround that worked.

I also understand that it may require some more work on your side to achieve the goal of splitting everything into templates, using the extends keyword and so on, so it may also not be a feasible transition for you.

**Comment by vtbassmatt** [comment]
In order to consolidate to fewer feedback channels, we've moved suggestions and issue reporting to [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). Sorry for the delay/confusion.
