### ISSUE TITLE
It is possible to convert a json to variables/parameters YAML and iterate?

### ISSUE THREAD

**Issue by giseliramos** [microsoft/azure-pipelines-yaml#599]
Hello,

I have a powershell script in a stage that creates a jsonObject and I save it to a variable to be reused later:
```
$imagesJson = @"
[
{
   "myAcr": "someCustomAcr1",
   "listImages": "image1, image2"
},
{
   "myAcr": "someCustomAcr2",
   "listImages": "image4, image5, image6"
}
]
"@

# < some operations I do on imagesObj, already converted >

$newJson = ConvertTo-Json $imagesObj -Compress
"##vso[task.setvariable variable=ImagesList;isOutput=true]$newJson"
```
This part works okay. The matter is that I want to populate some YAML variables with it or iterate, for example, I want to iterate for each "dict" here and extract the info. Is that possible to do in the YAML, to populate on variables or on parameters template?

Thanks!

**Comment by KonstantinTyukalov** [comment]
Hi @giseliramos, because these are runtime pipeline variables, you can't use YAML template syntax (which is compile-time) with them.
More info about runtime(+macro) and compile variables and differences between them shared in this [doc](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#understand-variable-syntax)

Could you clarify your use case with more details? Probably we'll be able to find a suitable solution for you

**Comment by max-zaytsev** [comment]
Such questions should be posted on [the Developer Community](https://developercommunity.visualstudio.com/home), since this repo is mainly about the templates located in this repository.
